// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAAr8YAiooSZMpdbpWbmXzLnBzSn86ttI',
    appId: '1:125098784362:web:344c2d839a371497217c13',
    messagingSenderId: '125098784362',
    projectId: 'chatapplication-e12c6',
    authDomain: 'chatapplication-e12c6.firebaseapp.com',
    storageBucket: 'chatapplication-e12c6.firebasestorage.app',
    measurementId: 'G-Y0L7SV7D9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRW4y2ksJD1mRhc6LnbKyRHxmBtgFp2ZU',
    appId: '1:125098784362:android:450ca992daff1906217c13',
    messagingSenderId: '125098784362',
    projectId: 'chatapplication-e12c6',
    storageBucket: 'chatapplication-e12c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX07f_mQpG4WA9oTCEbsaMBAM5dOglZ3k',
    appId: '1:125098784362:ios:807c1889f4d362b7217c13',
    messagingSenderId: '125098784362',
    projectId: 'chatapplication-e12c6',
    storageBucket: 'chatapplication-e12c6.firebasestorage.app',
    iosBundleId: 'com.example.projectChatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX07f_mQpG4WA9oTCEbsaMBAM5dOglZ3k',
    appId: '1:125098784362:ios:807c1889f4d362b7217c13',
    messagingSenderId: '125098784362',
    projectId: 'chatapplication-e12c6',
    storageBucket: 'chatapplication-e12c6.firebasestorage.app',
    iosBundleId: 'com.example.projectChatapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAAr8YAiooSZMpdbpWbmXzLnBzSn86ttI',
    appId: '1:125098784362:web:c4df76cfafb13eea217c13',
    messagingSenderId: '125098784362',
    projectId: 'chatapplication-e12c6',
    authDomain: 'chatapplication-e12c6.firebaseapp.com',
    storageBucket: 'chatapplication-e12c6.firebasestorage.app',
    measurementId: 'G-LV4F9JF7JP',
  );
}
